# Site settings
title: Walter Bolitto Carvalho
description: |
  Louis Rassaby is a NYC-based software engineer and entrepreneur currently at Google.
  He's the founder of Wirefreight, a customer service platform for freight. Previously, Louis led the new products engineering team
  at Phosphorus Genomics.

url: https://bolitto.github.io/

about_title: Sobre
projects_title: Página Inicial

# User settings
user_description_appendix: |
  I created this site to write about my interests: startups and entrepreneurship, design, data-intensive applications,
  functional programming, AR/VR, and machine learning. I like to use computers to solve problems.

  I built this site in [Jekyll][jekyll], and it's hosted for free on [GitHub Pages][gh-pages]. It's open source, so if
  you like it, feel free to fork it on [GitHub][github] and make your own version.


email: bolitto.walter@gmail.com
linkedin: walter-bolitto-carvalho-851290120
github: bolitto
#angellist: rassaby

relevant_tags: ['jogos', 'aulas', 'outros']

resume_url: https://bolitto.github.io/cv/

author: Walter Bolitto Carvalho
author_title: 
author_photo: photo.jpeg
user_description_short: |
  Sou educador e desenvolvedor de jogos e moro em São Paulo. Tenho experiência com game design, tecnologias voltadas a educação e campanhas, comunicação digital e análise de dados. Pós-graduando em Educação e Tecnologia pela Universidade Federal de São Carlos.

keywords: 'bolitto,walter bolitto,walter bolitto carvalho,educação,board games,jogos,educação e tecnologia'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/sobre'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
